### ISSUE TITLE
Getting Cloudflare challenge screen when calling https://www.nctx.co.uk/stops/3390SH15

### ISSUE THREAD

**Issue by coding-to-music** [simonprickett/nctx-stop-api#3]
In Postman or Thunder Client (vs code extension) running a GET for https://www.nctx.co.uk/stops/3390SH15

shows a challenge question

I saw it when I tried the first time via browser

However, my worker seems to be working at the moment:

https://cloudflare-nctx-bus-stop-api.coding-to-music.workers.dev/?stopId=3390FO07

Cool project btw, my repo is here 

https://github.com/coding-to-music/cloudflare-nctx-bus-stop-api

When they give 503 with the Cloudflare challenge then my worker returns null for the stops

**Comment by simonprickett** [comment]
Hi there - thanks for getting in touch, glad you found the project useful, do you have plans to build a front end or something?

Thanks for letting me know about the 503, that may explain why I sometimes see `null` responses, and why people outside of the UK have reported this too.  As I am effectively screen scraping the bus company's site, I guess this sort of thing is to be expected periodically.  I'll have a play with things like specifying a user agent when I fetch the source for their page and see if that makes it look less suspect to Cloudflare.

**Comment by coding-to-music** [comment]
I read about your tool on the Cloudflare blog, funny that now the bus company is using a different Cloudflare tool to "protect" their site, but it's more hobbyist use, and really they should not block every bot attempt, just block excessive attempts.

**Comment by coding-to-music** [comment]
I'm copying this Gatsby site today, it's one of the best sites I've seen and looks like it could be modified for many uses, such as the bus api

https://github.com/coding-to-music/spacexstats-gatsby-chartjs

You might reach out to the bus company and tell them your scraper got some good press and please stop blocking innocent uses...

**Comment by simonprickett** [comment]
Thanks - I will definitely reach out to them but will try a few tactics to look like a normal browser first - I didn't know I'd made the Cloudflare blog, do you happen to have a link as I am struggling to find one?

**Comment by simonprickett** [comment]
The SpaceX site looks great BTW.

**Comment by coding-to-music** [comment]
They called it train departures, at the bottom https://blog.cloudflare.com/platform-week-2022-wrap-up/

**Comment by coding-to-music** [comment]
This one is cool, I think API's and feeds are recommended rather than scraping because the page inevitably changes

https://github.com/coding-to-music/stm-gtfs-realtime
